//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeedee.Client.Web.Tests.ChangesetRepositoryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smeedee.org", ConfigurationName="ChangesetRepositoryService.ChangesetRepositoryService")]
    public interface ChangesetRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smeedee.org/ChangesetRepositoryService/Get", ReplyAction="http://smeedee.org/ChangesetRepositoryService/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.SourceControl.ChangesetsForUserSpecification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.SourceControl.AllChangesetsSpecification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.SourceControl.ChangesetsAfterRevisionSpecification))]
        Smeedee.DomainModel.SourceControl.Changeset[] Get(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.SourceControl.Changeset> specification);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChangesetRepositoryServiceChannel : Smeedee.Client.Web.Tests.ChangesetRepositoryService.ChangesetRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChangesetRepositoryServiceClient : System.ServiceModel.ClientBase<Smeedee.Client.Web.Tests.ChangesetRepositoryService.ChangesetRepositoryService>, Smeedee.Client.Web.Tests.ChangesetRepositoryService.ChangesetRepositoryService {
        
        public ChangesetRepositoryServiceClient() {
        }
        
        public ChangesetRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChangesetRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChangesetRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChangesetRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Smeedee.DomainModel.SourceControl.Changeset[] Get(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.SourceControl.Changeset> specification) {
            return base.Channel.Get(specification);
        }
    }
}
