//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeedee.Client.Web.Tests.VCSCredentialsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smeedee.org", ConfigurationName="VCSCredentialsService.VCSCredentialsService")]
    public interface VCSCredentialsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smeedee.org/VCSCredentialsService/Check", ReplyAction="http://smeedee.org/VCSCredentialsService/CheckResponse")]
        bool Check(string provider, string url, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VCSCredentialsServiceChannel : Smeedee.Client.Web.Tests.VCSCredentialsService.VCSCredentialsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VCSCredentialsServiceClient : System.ServiceModel.ClientBase<Smeedee.Client.Web.Tests.VCSCredentialsService.VCSCredentialsService>, Smeedee.Client.Web.Tests.VCSCredentialsService.VCSCredentialsService {
        
        public VCSCredentialsServiceClient() {
        }
        
        public VCSCredentialsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VCSCredentialsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VCSCredentialsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VCSCredentialsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Check(string provider, string url, string username, string password) {
            return base.Channel.Check(provider, url, username, password);
        }
    }
}
