//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SelectWidgetsDialogSampleSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SelectWidgetsDialogSampleSource { }
#else

	public class SelectWidgetsDialogSampleSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public SelectWidgetsDialogSampleSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/Smeedee.Client.Framework.SL;component/SampleData/SelectWidgetsDialogSampleSource/SelectWidgetsDialogSampleSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private FilteredWidgets _FilteredWidgets = new FilteredWidgets();

		public FilteredWidgets FilteredWidgets
		{
			get
			{
				return this._FilteredWidgets;
			}
		}
	}

	public class FilteredWidgetsItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Name = string.Empty;

		public string Name
		{
			get
			{
				return this._Name;
			}

			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}

		private string _Description = string.Empty;

		public string Description
		{
			get
			{
				return this._Description;
			}

			set
			{
				if (this._Description != value)
				{
					this._Description = value;
					this.OnPropertyChanged("Description");
				}
			}
		}

		private double _SecondsOnScreen = 0;

		public double SecondsOnScreen
		{
			get
			{
				return this._SecondsOnScreen;
			}

			set
			{
				if (this._SecondsOnScreen != value)
				{
					this._SecondsOnScreen = value;
					this.OnPropertyChanged("SecondsOnScreen");
				}
			}
		}

		private bool _IsDescriptionCapped = false;

		public bool IsDescriptionCapped
		{
			get
			{
				return this._IsDescriptionCapped;
			}

			set
			{
				if (this._IsDescriptionCapped != value)
				{
					this._IsDescriptionCapped = value;
					this.OnPropertyChanged("IsDescriptionCapped");
				}
			}
		}
	}

	public class FilteredWidgets : System.Collections.ObjectModel.ObservableCollection<FilteredWidgetsItem>
	{ 
	}
#endif
}
