//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeedee.Integration.Tests.CI.TeamCity {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TeamCityResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TeamCityResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Smeedee.Integration.Tests.CI.TeamCity.TeamCityResources", typeof(TeamCityResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;project webUrl=&quot;http://smeedee.com:8111/project.html?projectId=project2&quot; description=&quot;&quot; archived=&quot;false&quot; name=&quot;Smeedee&quot; id=&quot;project2&quot; href=&quot;/httpAuth/app/rest/projects/id:project2&quot;&gt;&lt;buildTypes&gt;&lt;buildType id=&quot;bt5&quot; name=&quot;Summer of Code 2010 - Oslo&quot; href=&quot;/httpAuth/app/rest/buildTypes/id:bt5&quot; projectName=&quot;Smeedee&quot; projectId=&quot;project2&quot; webUrl=&quot;http://smeedee.com:8111/viewType.html?buildTypeId=bt5&quot;/&gt;&lt;buildType id=&quot;bt6&quot; name=&quot;Summer of Code 2010 - Stavanger&quot; href=&quot;/httpAuth/app/rest/buildTypes/id:bt6&quot; projectNam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetBuildconfigurations {
            get {
                return ResourceManager.GetString("GetBuildconfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;build id=&quot;90&quot; number=&quot;35&quot; status=&quot;FAILURE&quot; href=&quot;/httpAuth/app/rest/builds/id:90&quot; webUrl=&quot;http://smeedee.com:8111/viewLog.html?buildId=90&amp;amp;buildTypeId=bt4&quot; personal=&quot;false&quot; history=&quot;false&quot; pinned=&quot;false&quot;&gt;&lt;statusText&gt;Tests failed: 2, passed: 427, ignored: 46&lt;/statusText&gt;&lt;buildType id=&quot;bt4&quot; name=&quot;Summer of Code 2010 - Trondheim&quot; href=&quot;/httpAuth/app/rest/buildTypes/id:bt4&quot; projectName=&quot;Smeedee&quot; projectId=&quot;project2&quot; webUrl=&quot;http://smeedee.com:8111/viewType.html?buildTypeId=bt4&quot;/&gt;&lt;startDate&gt;20100626T235650+0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetBuildinfo {
            get {
                return ResourceManager.GetString("GetBuildinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;builds count=&quot;25&quot;&gt;&lt;build id=&quot;88&quot; number=&quot;25&quot; status=&quot;FAILURE&quot; buildTypeId=&quot;bt6&quot; href=&quot;/httpAuth/app/rest/builds/id:88&quot; webUrl=&quot;http://smeedee.com:8111/viewLog.html?buildId=88&amp;amp;buildTypeId=bt6&quot;/&gt;&lt;build id=&quot;86&quot; number=&quot;24&quot; status=&quot;SUCCESS&quot; buildTypeId=&quot;bt6&quot; href=&quot;/httpAuth/app/rest/builds/id:86&quot; webUrl=&quot;http://smeedee.com:8111/viewLog.html?buildId=86&amp;amp;buildTypeId=bt6&quot;/&gt;&lt;build id=&quot;84&quot; number=&quot;23&quot; status=&quot;SUCCESS&quot; buildTypeId=&quot;bt6&quot; href=&quot;/httpAuth/app/rest/builds/id:84&quot; webUrl=&quot;http://smeedee.com:8111/vi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetBuilds {
            get {
                return ResourceManager.GetString("GetBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;changes count=&quot;2&quot;&gt;&lt;change version=&quot;445&quot; id=&quot;114&quot; href=&quot;/httpAuth/app/rest/changes/id:114&quot;/&gt;&lt;change version=&quot;445&quot; id=&quot;114&quot; href=&quot;/httpAuth/app/rest/changes/id:114&quot;/&gt;&lt;/changes&gt;.
        /// </summary>
        internal static string GetChanges {
            get {
                return ResourceManager.GetString("GetChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;change username=&quot;d.nyvik&quot; date=&quot;20100626T173216+0200&quot; version=&quot;445&quot; id=&quot;114&quot; href=&quot;/httpAuth/app/rest/changes/id:114&quot;&gt;&lt;comment&gt;Fixed some functionality and added comments for students. Save function overwrites every DB except the one that is changed, needs to be addressed. More tests need to be written and some modified to cover new functionality.
        ///&lt;/comment&gt;&lt;files&gt;&lt;file relative-file=&quot;branches/soc/stavanger/source/Widget/Smeedee.Widget.TeamMembers.SL/View/UserdbSettingsView.xaml&quot; file=&quot;http://smeedee.goog [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetChangesetInfo {
            get {
                return ResourceManager.GetString("GetChangesetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;changes count=&quot;0&quot;/&gt;.
        /// </summary>
        internal static string GetChangesNoChanges {
            get {
                return ResourceManager.GetString("GetChangesNoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;projects&gt;&lt;project name=&quot;Smeedee&quot; id=&quot;project2&quot; href=&quot;/httpAuth/app/rest/projects/id:project2&quot;/&gt;&lt;project name=&quot;Jon Terje&quot; id=&quot;project3&quot; href=&quot;/httpAuth/app/rest/projects/id:project3&quot;/&gt;&lt;/projects&gt;.
        /// </summary>
        internal static string GetProjects {
            get {
                return ResourceManager.GetString("GetProjects", resourceCulture);
            }
        }
    }
}
