//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeedee.Client.Web.Tests.UserRepositoryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smeedee.org", ConfigurationName="UserRepositoryService.UserRepositoryService")]
    public interface UserRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smeedee.org/UserRepositoryService/Get", ReplyAction="http://smeedee.org/UserRepositoryService/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Framework.AllSpecification<Smeedee.DomainModel.Users.Userdb>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Users.UserdbNameSpecification))]
        Smeedee.DomainModel.Users.Userdb[] Get(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.Users.Userdb> specification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smeedee.org/UserRepositoryService/Save", ReplyAction="http://smeedee.org/UserRepositoryService/SaveResponse")]
        void Save(Smeedee.DomainModel.Users.Userdb userdb);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserRepositoryServiceChannel : Smeedee.Client.Web.Tests.UserRepositoryService.UserRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserRepositoryServiceClient : System.ServiceModel.ClientBase<Smeedee.Client.Web.Tests.UserRepositoryService.UserRepositoryService>, Smeedee.Client.Web.Tests.UserRepositoryService.UserRepositoryService {
        
        public UserRepositoryServiceClient() {
        }
        
        public UserRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Smeedee.DomainModel.Users.Userdb[] Get(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.Users.Userdb> specification) {
            return base.Channel.Get(specification);
        }
        
        public void Save(Smeedee.DomainModel.Users.Userdb userdb) {
            base.Channel.Save(userdb);
        }
    }
}
