//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeedee.Client.Web {
    
    
    public partial class Log {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// LogGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView LogGrid;

        //Lars-generated field, because I'm such a rebel, and because VS wouldn't do it for me.
        //The log page runs fine without this reference (when triggered to compile by a browser),
        //but when the Smeedee.Client.Web project is built from within VS, the compiler complains.
        //No idea what causes this, but adding this reference fixes it.
        protected global::System.Web.UI.WebControls.Button DeleteAllButton;
    }
}
