//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APD.Client.WebTests.SettingsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://agileprojectdashboard.org", ConfigurationName="SettingsService.SettingsService")]
    public interface SettingsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agileprojectdashboard.org/SettingsService/SaveSettings", ReplyAction="http://agileprojectdashboard.org/SettingsService/SaveSettingsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void SaveSettings(APD.Framework.Settings.Settings settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agileprojectdashboard.org/SettingsService/GetSettings", ReplyAction="http://agileprojectdashboard.org/SettingsService/GetSettingsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        APD.Framework.Settings.Settings GetSettings();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SettingsServiceChannel : APD.Client.WebTests.SettingsService.SettingsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SettingsServiceClient : System.ServiceModel.ClientBase<APD.Client.WebTests.SettingsService.SettingsService>, APD.Client.WebTests.SettingsService.SettingsService {
        
        public SettingsServiceClient() {
        }
        
        public SettingsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SettingsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SettingsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SettingsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SaveSettings(APD.Framework.Settings.Settings settings) {
            base.Channel.SaveSettings(settings);
        }
        
        public APD.Framework.Settings.Settings GetSettings() {
            return base.Channel.GetSettings();
        }
    }
}
