//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeedee.Client.Web.Tests.TeamPictureService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smeedee.org", ConfigurationName="TeamPictureService.TeamPictureRepositoryWebservice")]
    public interface TeamPictureRepositoryWebservice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smeedee.org/TeamPictureRepositoryWebservice/Get", ReplyAction="http://smeedee.org/TeamPictureRepositoryWebservice/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.TeamPicture.CurrentTeamPictureSpecification))]
        Smeedee.DomainModel.TeamPicture.TeamPicture[] Get(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.TeamPicture.TeamPicture> specification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smeedee.org/TeamPictureRepositoryWebservice/Save", ReplyAction="http://smeedee.org/TeamPictureRepositoryWebservice/SaveResponse")]
        void Save(Smeedee.DomainModel.TeamPicture.TeamPicture[] teamPictures);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TeamPictureRepositoryWebserviceChannel : Smeedee.Client.Web.Tests.TeamPictureService.TeamPictureRepositoryWebservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TeamPictureRepositoryWebserviceClient : System.ServiceModel.ClientBase<Smeedee.Client.Web.Tests.TeamPictureService.TeamPictureRepositoryWebservice>, Smeedee.Client.Web.Tests.TeamPictureService.TeamPictureRepositoryWebservice {
        
        public TeamPictureRepositoryWebserviceClient() {
        }
        
        public TeamPictureRepositoryWebserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TeamPictureRepositoryWebserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeamPictureRepositoryWebserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeamPictureRepositoryWebserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Smeedee.DomainModel.TeamPicture.TeamPicture[] Get(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.TeamPicture.TeamPicture> specification) {
            return base.Channel.Get(specification);
        }
        
        public void Save(Smeedee.DomainModel.TeamPicture.TeamPicture[] teamPictures) {
            base.Channel.Save(teamPictures);
        }
    }
}
