//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeedee.Client.Web.Tests.HolidayRepositoryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smeedee.org", ConfigurationName="HolidayRepositoryService.HolidayRepositoryService")]
    public interface HolidayRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smeedee.org/HolidayRepositoryService/Get", ReplyAction="http://smeedee.org/HolidayRepositoryService/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Holidays.HolidaySpecification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Framework.AllSpecification<Smeedee.DomainModel.Holidays.Holiday>))]
        Smeedee.DomainModel.Holidays.Holiday[] Get(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.Holidays.Holiday> specification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smeedee.org/HolidayRepositoryService/Save", ReplyAction="http://smeedee.org/HolidayRepositoryService/SaveResponse")]
        void Save(Smeedee.DomainModel.Holidays.Holiday[] holidays);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HolidayRepositoryServiceChannel : Smeedee.Client.Web.Tests.HolidayRepositoryService.HolidayRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HolidayRepositoryServiceClient : System.ServiceModel.ClientBase<Smeedee.Client.Web.Tests.HolidayRepositoryService.HolidayRepositoryService>, Smeedee.Client.Web.Tests.HolidayRepositoryService.HolidayRepositoryService {
        
        public HolidayRepositoryServiceClient() {
        }
        
        public HolidayRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HolidayRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidayRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidayRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Smeedee.DomainModel.Holidays.Holiday[] Get(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.Holidays.Holiday> specification) {
            return base.Channel.Get(specification);
        }
        
        public void Save(Smeedee.DomainModel.Holidays.Holiday[] holidays) {
            base.Channel.Save(holidays);
        }
    }
}
