//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APD.Client.WebTests.CIRepositoryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://agileprojectdashboard.org", ConfigurationName="CIRepositoryService.CIRepositoryService")]
    public interface CIRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://agileprojectdashboard.org/CIRepositoryService/Get", ReplyAction="http://agileprojectdashboard.org/CIRepositoryService/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(APD.DomainModel.Framework.AllSpecification<APD.DomainModel.CI.CIServer>))]
        System.Collections.Generic.List<APD.DomainModel.CI.CIServer> Get(APD.DomainModel.Framework.Specification<APD.DomainModel.CI.CIServer> specification);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface CIRepositoryServiceChannel : APD.Client.WebTests.CIRepositoryService.CIRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CIRepositoryServiceClient : System.ServiceModel.ClientBase<APD.Client.WebTests.CIRepositoryService.CIRepositoryService>, APD.Client.WebTests.CIRepositoryService.CIRepositoryService {
        
        public CIRepositoryServiceClient() {
        }
        
        public CIRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CIRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<APD.DomainModel.CI.CIServer> Get(APD.DomainModel.Framework.Specification<APD.DomainModel.CI.CIServer> specification) {
            return base.Channel.Get(specification);
        }
    }
}
