//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeedee.Client.Web.Tests.SlideConfigurationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="SlideConfigurationService.SlideConfigurationRepositoryService")]
    public interface SlideConfigurationRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SlideConfigurationRepositoryService/Get", ReplyAction="urn:SlideConfigurationRepositoryService/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Config.SlideConfig.SlideConfigurationByIdSpecification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Framework.AllSpecification<Smeedee.DomainModel.Config.SlideConfig.SlideConfiguration>))]
        System.Collections.Generic.List<Smeedee.DomainModel.Config.SlideConfig.SlideConfiguration> Get(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.Config.SlideConfig.SlideConfiguration> specification);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SlideConfigurationRepositoryService/Save", ReplyAction="urn:SlideConfigurationRepositoryService/SaveResponse")]
        void Save(Smeedee.DomainModel.Config.SlideConfig.SlideConfiguration configuration);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SlideConfigurationRepositoryService/Delete", ReplyAction="urn:SlideConfigurationRepositoryService/DeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Config.SlideConfig.SlideConfigurationByIdSpecification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Framework.AllSpecification<Smeedee.DomainModel.Config.SlideConfig.SlideConfiguration>))]
        void Delete(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.Config.SlideConfig.SlideConfiguration> specification);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SlideConfigurationRepositoryServiceChannel : Smeedee.Client.Web.Tests.SlideConfigurationService.SlideConfigurationRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SlideConfigurationRepositoryServiceClient : System.ServiceModel.ClientBase<Smeedee.Client.Web.Tests.SlideConfigurationService.SlideConfigurationRepositoryService>, Smeedee.Client.Web.Tests.SlideConfigurationService.SlideConfigurationRepositoryService {
        
        public SlideConfigurationRepositoryServiceClient() {
        }
        
        public SlideConfigurationRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SlideConfigurationRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SlideConfigurationRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SlideConfigurationRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Smeedee.DomainModel.Config.SlideConfig.SlideConfiguration> Get(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.Config.SlideConfig.SlideConfiguration> specification) {
            return base.Channel.Get(specification);
        }
        
        public void Save(Smeedee.DomainModel.Config.SlideConfig.SlideConfiguration configuration) {
            base.Channel.Save(configuration);
        }
        
        public void Delete(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.Config.SlideConfig.SlideConfiguration> specification) {
            base.Channel.Delete(specification);
        }
    }
}
