//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APD.Client.WebTests.UserRepositoryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="UserRepositoryService.UserRepositoryService")]
    public interface UserRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UserRepositoryService/Get", ReplyAction="urn:UserRepositoryService/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(APD.DomainModel.Framework.AllSpecification<APD.DomainModel.Users.Userdb>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(APD.DomainModel.Users.UserdbNameSpecification))]
        System.Collections.Generic.List<APD.DomainModel.Users.Userdb> Get(APD.DomainModel.Framework.Specification<APD.DomainModel.Users.Userdb> specification);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UserRepositoryService/Save", ReplyAction="urn:UserRepositoryService/SaveResponse")]
        void Save(APD.DomainModel.Users.Userdb userdb);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserRepositoryServiceChannel : APD.Client.WebTests.UserRepositoryService.UserRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserRepositoryServiceClient : System.ServiceModel.ClientBase<APD.Client.WebTests.UserRepositoryService.UserRepositoryService>, APD.Client.WebTests.UserRepositoryService.UserRepositoryService {
        
        public UserRepositoryServiceClient() {
        }
        
        public UserRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<APD.DomainModel.Users.Userdb> Get(APD.DomainModel.Framework.Specification<APD.DomainModel.Users.Userdb> specification) {
            return base.Channel.Get(specification);
        }
        
        public void Save(APD.DomainModel.Users.Userdb userdb) {
            base.Channel.Save(userdb);
        }
    }
}
