//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeedee.Client.Web.Tests.CIRepositoryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smeedee.org", ConfigurationName="CIRepositoryService.CIRepositoryService")]
    public interface CIRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smeedee.org/CIRepositoryService/Get", ReplyAction="http://smeedee.org/CIRepositoryService/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Framework.AllSpecification<Smeedee.DomainModel.CI.CIServer>))]
        Smeedee.DomainModel.CI.CIServer[] Get(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.CI.CIServer> specification);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CIRepositoryServiceChannel : Smeedee.Client.Web.Tests.CIRepositoryService.CIRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CIRepositoryServiceClient : System.ServiceModel.ClientBase<Smeedee.Client.Web.Tests.CIRepositoryService.CIRepositoryService>, Smeedee.Client.Web.Tests.CIRepositoryService.CIRepositoryService {
        
        public CIRepositoryServiceClient() {
        }
        
        public CIRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CIRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Smeedee.DomainModel.CI.CIServer[] Get(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.CI.CIServer> specification) {
            return base.Channel.Get(specification);
        }
    }
}
