//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APD.Client.WebTests.LogEntryRepositoryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="LogEntryRepositoryService.LogEntryRepositoryService")]
    public interface LogEntryRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LogEntryRepositoryService/Log", ReplyAction="urn:LogEntryRepositoryService/LogResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(APD.DomainModel.Framework.Logging.ErrorLogEntry))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(APD.DomainModel.Framework.Logging.WarningLogEntry))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(APD.DomainModel.Framework.Logging.InfoLogEntry))]
        void Log(APD.DomainModel.Framework.Logging.LogEntry logEntry);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LogEntryRepositoryService/Get", ReplyAction="urn:LogEntryRepositoryService/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(APD.DomainModel.Framework.AllSpecification<APD.DomainModel.Framework.Logging.LogEntry>))]
        APD.DomainModel.Framework.Logging.LogEntry[] Get(APD.DomainModel.Framework.Specification<APD.DomainModel.Framework.Logging.LogEntry> specification);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface LogEntryRepositoryServiceChannel : APD.Client.WebTests.LogEntryRepositoryService.LogEntryRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class LogEntryRepositoryServiceClient : System.ServiceModel.ClientBase<APD.Client.WebTests.LogEntryRepositoryService.LogEntryRepositoryService>, APD.Client.WebTests.LogEntryRepositoryService.LogEntryRepositoryService {
        
        public LogEntryRepositoryServiceClient() {
        }
        
        public LogEntryRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogEntryRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogEntryRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogEntryRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Log(APD.DomainModel.Framework.Logging.LogEntry logEntry) {
            base.Channel.Log(logEntry);
        }
        
        public APD.DomainModel.Framework.Logging.LogEntry[] Get(APD.DomainModel.Framework.Specification<APD.DomainModel.Framework.Logging.LogEntry> specification) {
            return base.Channel.Get(specification);
        }
    }
}
