//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeedee.Client.Web.Tests.LogEntryRepositoryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smeedee.org", ConfigurationName="LogEntryRepositoryService.LogEntryRepositoryService")]
    public interface LogEntryRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smeedee.org/LogEntryRepositoryService/Log", ReplyAction="http://smeedee.org/LogEntryRepositoryService/LogResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Framework.Logging.ErrorLogEntry))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Framework.Logging.WarningLogEntry))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Framework.Logging.InfoLogEntry))]
        void Log(Smeedee.DomainModel.Framework.Logging.LogEntry logEntry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smeedee.org/LogEntryRepositoryService/Get", ReplyAction="http://smeedee.org/LogEntryRepositoryService/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Framework.AllSpecification<Smeedee.DomainModel.Framework.Logging.LogEntry>))]
        Smeedee.DomainModel.Framework.Logging.LogEntry[] Get(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.Framework.Logging.LogEntry> specification);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LogEntryRepositoryServiceChannel : Smeedee.Client.Web.Tests.LogEntryRepositoryService.LogEntryRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogEntryRepositoryServiceClient : System.ServiceModel.ClientBase<Smeedee.Client.Web.Tests.LogEntryRepositoryService.LogEntryRepositoryService>, Smeedee.Client.Web.Tests.LogEntryRepositoryService.LogEntryRepositoryService {
        
        public LogEntryRepositoryServiceClient() {
        }
        
        public LogEntryRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogEntryRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogEntryRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogEntryRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Log(Smeedee.DomainModel.Framework.Logging.LogEntry logEntry) {
            base.Channel.Log(logEntry);
        }
        
        public Smeedee.DomainModel.Framework.Logging.LogEntry[] Get(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.Framework.Logging.LogEntry> specification) {
            return base.Channel.Get(specification);
        }
    }
}
