//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeedee.Client.Web.Tests.TaskDefRepositoryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smeedee.org", ConfigurationName="TaskDefRepositoryService.TaskDefinitionRepositoryService")]
    public interface TaskDefinitionRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smeedee.org/TaskDefinitionRepositoryService/Get", ReplyAction="http://smeedee.org/TaskDefinitionRepositoryService/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Framework.AllSpecification<Smeedee.DomainModel.TaskDefinition.TaskDefinition>))]
        System.Collections.Generic.List<Smeedee.DomainModel.TaskDefinition.TaskDefinition> Get(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.TaskDefinition.TaskDefinition> specification);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TaskDefinitionRepositoryServiceChannel : Smeedee.Client.Web.Tests.TaskDefRepositoryService.TaskDefinitionRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaskDefinitionRepositoryServiceClient : System.ServiceModel.ClientBase<Smeedee.Client.Web.Tests.TaskDefRepositoryService.TaskDefinitionRepositoryService>, Smeedee.Client.Web.Tests.TaskDefRepositoryService.TaskDefinitionRepositoryService {
        
        public TaskDefinitionRepositoryServiceClient() {
        }
        
        public TaskDefinitionRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaskDefinitionRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskDefinitionRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskDefinitionRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Smeedee.DomainModel.TaskDefinition.TaskDefinition> Get(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.TaskDefinition.TaskDefinition> specification) {
            return base.Channel.Get(specification);
        }
    }
}
