//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making 
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.WorkingDaysLeftDataSource
{
	using System;

	public class WorkingDaysLeftDataSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public WorkingDaysLeftDataSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/Smeedee.Client.Widget.ProjectInfo.SL;component/SampleData/WorkingDaysLeftDataSource/WorkingDaysLeftDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception )
			{ }
		}

		private string _DaysRemaining = string.Empty;
		public string DaysRemaining
		{
			get
			{
				return this._DaysRemaining;
			}
			set
			{
				if (this._DaysRemaining != value)
				{
					this._DaysRemaining = value;
					this.OnPropertyChanged("DaysRemainingTextSmall");
				}
			}
		}
	}
}
