//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APD.IntegrationTests.PMT.RallyDev.DomainModel.Repositories {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APD.IntegrationTests.PMT.RallyDev.DomainModel.Repositories.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Iteration rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot; ref=&quot;https://community.rallydev.com/slm/webservice/1.13/iteration/290873918&quot; objectVersion=&quot;3&quot; refObjectName=&quot;Iteration 0&quot; CreatedAt=&quot;Jan 22&quot;&gt;
        ///  &lt;CreationDate&gt;2009-01-22T08:15:48.000Z&lt;/CreationDate&gt;
        ///  &lt;ObjectID&gt;290873918&lt;/ObjectID&gt;
        ///  &lt;Subscription rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot; ref=&quot;https://community.rallydev.com/slm/webservice/1.13/subscription/290873179&quot; refObjectName=&quot;Community Edition - Myself Inc - mail@go [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Iteration {
            get {
                return ResourceManager.GetString("Iteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;QueryResult rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot;&gt;
        ///  &lt;Errors/&gt;
        ///  &lt;Warnings/&gt;
        ///  &lt;TotalResultCount&gt;5&lt;/TotalResultCount&gt;
        ///  &lt;StartIndex&gt;1&lt;/StartIndex&gt;
        ///  &lt;PageSize&gt;20&lt;/PageSize&gt;
        ///  
        ///  &lt;Results&gt;
        ///    &lt;Object rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot; ref=&quot;https://community.rallydev.com/slm/webservice/1.13/iteration/290873918&quot; refObjectName=&quot;Iteration 0&quot; type=&quot;Iteration&quot;/&gt;
        ///    &lt;Object rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot; ref=&quot;https://community.rallydev.com/slm/webservice/1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IterationsForProject {
            get {
                return ResourceManager.GetString("IterationsForProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Taskas rallyAPIMaj&lt;/ObjectID&gt;
        ///	&lt;Subscription rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot; ref=&quot;https://community.rallydev.com/slm/webservice/1.13/subscription/290873179&quot; refObjectName=&quot;Community Edition - Myself Inc - mail@goeran.no&quot; type=&quot;Subscription&quot;/&gt;
        ///	&lt;Wor
        ///		HAve 15-20 mintues speed date interviews with the students
        ///	&lt;/Description&gt;
        ///	&lt;Discussio
        ///	&lt;State&gt;Defined&lt;/State&gt;
        ///	&lt;TaskIndex&gt;1&lt;/TaskIndex&gt;
        ///	&lt;WorkProduct rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot; ref=&quot;https://community.rallydev.com/slm/webservice/1.13/hie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Malformed {
            get {
                return ResourceManager.GetString("Malformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;QueryResult rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot;&gt;
        ///  &lt;Errors/&gt;
        ///  &lt;Warnings/&gt;
        ///  &lt;TotalResultCount&gt;1&lt;/TotalResultCount&gt;
        ///  &lt;StartIndex&gt;1&lt;/StartIndex&gt;
        ///  &lt;PageSize&gt;20&lt;/PageSize&gt;
        ///  −
        ///  &lt;Results&gt;
        ///    &lt;Object rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot; ref=&quot;https://community.rallydev.com/slm/webservice/1.13/project/290873262&quot; refObjectName=&quot;Continuous Project Monitor&quot; type=&quot;Project&quot;/&gt;
        ///  &lt;/Results&gt;
        ///&lt;/QueryResult&gt;.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;Project rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot; ref=&quot;https://community.rallydev.com/slm/webservice/1.13/project/290873262&quot; objectVersion=&quot;2&quot; refObjectName=&quot;Continuous Project Monitor&quot; CreatedAt=&quot;Jan 22&quot;&gt;
        ///	&lt;CreationDate&gt;2009-01-22T08:15:30.000Z&lt;/CreationDate&gt;
        ///	&lt;ObjectID&gt;290873262&lt;/ObjectID&gt;
        ///	&lt;Subscription rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot; ref=&quot;https://community.rallydev.com/slm/webservice/1.13/subscription/290873179&quot; refObjectName=&quot;Community Edition - Myself Inc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectWithData {
            get {
                return ResourceManager.GetString("ProjectWithData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;QueryResult rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot;&gt;
        ///	&lt;Errors/&gt;
        ///	&lt;Warnings/&gt;
        ///	&lt;TotalResultCount&gt;110&lt;/TotalResultCount&gt;
        ///	&lt;StartIndex&gt;1&lt;/StartIndex&gt;
        ///	&lt;PageSize&gt;100&lt;/PageSize&gt;
        ///
        ///	&lt;Results&gt;
        ///		&lt;Object rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot; ref=&quot;https://community.rallydev.com/slm/webservice/1.13/task/290873986&quot; refObjectName=&quot;Update User Stories&quot; type=&quot;Task&quot;/&gt;
        ///		&lt;Object rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot; ref=&quot;https://community.rallydev.com/slm/webservice/1.13/tas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryResultWithMoreResultsThenPageSize {
            get {
                return ResourceManager.GetString("QueryResultWithMoreResultsThenPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;RevisionHistory rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot; ref=&quot;https://community.rallydev.com/slm/webservice/1.13/revisionhistory/497955718&quot; objectVersion=&quot;1&quot; CreatedAt=&quot;Jul 28&quot;&gt;
        ///	&lt;CreationDate&gt;2009-07-28T11:25:08.000Z&lt;/CreationDate&gt;
        ///	&lt;ObjectID&gt;497955718&lt;/ObjectID&gt;
        ///	&lt;Subscription rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot; ref=&quot;https://community.rallydev.com/slm/webservice/1.13/subscription/290873179&quot; refObjectName=&quot;Community Edition - Myself Inc - mail@goeran.no&quot; type=&quot;Subs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RevisionHistory {
            get {
                return ResourceManager.GetString("RevisionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;QueryResult rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot;&gt;
        ///  &lt;Errors/&gt;
        ///  &lt;Warnings/&gt;
        ///  &lt;TotalResultCount&gt;1&lt;/TotalResultCount&gt;
        ///  &lt;StartIndex&gt;1&lt;/StartIndex&gt;
        ///  &lt;PageSize&gt;20&lt;/PageSize&gt;
        ///  
        ///  &lt;Results&gt;
        ///    &lt;Object rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot; ref=&quot;https://community.rallydev.com/slm/webservice/1.13/task/290873986&quot; refObjectName=&quot;Update User Stories&quot; type=&quot;Task&quot;/&gt;
        ///  &lt;/Results&gt;
        ///&lt;/QueryResult&gt;.
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;QueryResult rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot;&gt;
        ///  &lt;Errors/&gt;
        ///  &lt;Warnings/&gt;
        ///  &lt;TotalResultCount&gt;9&lt;/TotalResultCount&gt;
        ///  &lt;StartIndex&gt;1&lt;/StartIndex&gt;
        ///  &lt;PageSize&gt;20&lt;/PageSize&gt;
        ///  
        ///  &lt;Results&gt;
        ///    &lt;Object rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot; ref=&quot;https://community.rallydev.com/slm/webservice/1.13/task/290873986&quot; refObjectName=&quot;Update User Stories&quot; type=&quot;Task&quot;/&gt;
        ///    &lt;Object rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot; ref=&quot;https://community.rallydev.com/slm/webservice/1.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TasksForIteration {
            get {
                return ResourceManager.GetString("TasksForIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Task rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot; ref=&quot;https://community.rallydev.com/slm/webservice/1.13/task/290873986&quot; objectVersion=&quot;1&quot; refObjectName=&quot;Update User Stories&quot; CreatedAt=&quot;Jan 22&quot;&gt;
        ///  &lt;CreationDate&gt;2009-01-22T08:15:49.000Z&lt;/CreationDate&gt;
        ///  &lt;ObjectID&gt;290873986&lt;/ObjectID&gt;
        ///  &lt;Subscription rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot; ref=&quot;https://community.rallydev.com/slm/webservice/1.13/subscription/290873179&quot; refObjectName=&quot;Community Edition - Myself Inc - mail@goer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TaskWithData {
            get {
                return ResourceManager.GetString("TaskWithData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;Task rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot; ref=&quot;https://community.rallydev.com/slm/webservice/1.13/task/295139730&quot; objectVersion=&quot;1&quot; refObjectName=&quot;Job interview with students&quot; CreatedAt=&quot;Jan 27&quot;&gt;
        ///	&lt;CreationDate&gt;2009-01-27T10:14:27.000Z&lt;/CreationDate&gt;
        ///	&lt;ObjectID&gt;295139730&lt;/ObjectID&gt;
        ///	&lt;Subscription rallyAPIMajor=&quot;1&quot; rallyAPIMinor=&quot;13&quot; ref=&quot;https://community.rallydev.com/slm/webservice/1.13/subscription/290873179&quot; refObjectName=&quot;Community Edition - Myself Inc - mai [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
    }
}
