//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.RetrospectiveNotesSampleData
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class RetrospectiveNotesSampleData { }
#else

	public class RetrospectiveNotesSampleData : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public RetrospectiveNotesSampleData()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/Smeedee.Widget.Corkboard.SL;component/SampleData/RetrospectiveNotesSampleData/RetrospectiveNotesSampleData.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private PositiveNotes _PositiveNotes = new PositiveNotes();

		public PositiveNotes PositiveNotes
		{
			get
			{
				return this._PositiveNotes;
			}
		}

		private NegativeNotes _NegativeNotes = new NegativeNotes();

		public NegativeNotes NegativeNotes
		{
			get
			{
				return this._NegativeNotes;
			}
		}

		private ComplexPropertyType _ComplexProperty = new ComplexPropertyType();

		public ComplexPropertyType ComplexProperty
		{
			get
			{
				return this._ComplexProperty;
			}

			set
			{
				if (this._ComplexProperty != value)
				{
					this._ComplexProperty = value;
					this.OnPropertyChanged("ComplexProperty");
				}
			}
		}
	}

	public class PositiveNotes : System.Collections.ObjectModel.ObservableCollection<PositiveNotesItem>
	{ 
	}

	public class PositiveNotesItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Description = string.Empty;

		public string Description
		{
			get
			{
				return this._Description;
			}

			set
			{
				if (this._Description != value)
				{
					this._Description = value;
					this.OnPropertyChanged("Description");
				}
			}
		}

		private double _RandomAngel = 0;

		public double RandomAngel
		{
			get
			{
				return this._RandomAngel;
			}

			set
			{
				if (this._RandomAngel != value)
				{
					this._RandomAngel = value;
					this.OnPropertyChanged("RandomAngel");
				}
			}
		}
	}

	public class NegativeNotes : System.Collections.ObjectModel.ObservableCollection<NegativeNotesItem>
	{ 
	}

	public class NegativeNotesItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Description = string.Empty;

		public string Description
		{
			get
			{
				return this._Description;
			}

			set
			{
				if (this._Description != value)
				{
					this._Description = value;
					this.OnPropertyChanged("Description");
				}
			}
		}

		private double _RandomAngel = 0;

		public double RandomAngel
		{
			get
			{
				return this._RandomAngel;
			}

			set
			{
				if (this._RandomAngel != value)
				{
					this._RandomAngel = value;
					this.OnPropertyChanged("RandomAngel");
				}
			}
		}
	}

	public class ComplexPropertyType : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private CollectionItemCollection _Collection = new CollectionItemCollection();

		public CollectionItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class CollectionItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	public class CollectionItemCollection : System.Collections.ObjectModel.ObservableCollection<CollectionItem>
	{ 
	}
#endif
}
