//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tskjortebutikken.Widgets.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tskjortebutikken.Widgets.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///	Name: &quot;Webshop&quot;,
        ///	Collections: [
        ///		{ Name: &quot;orders&quot;},
        ///		{ Name: &quot;ordersPrDay&quot;},
        ///		{ Name: &quot;revenuePrDay&quot;}	]
        ///},
        ///{
        ///	Name: &quot;Source Control&quot;,
        ///	Collections: [
        ///		{ Name: &quot;commitsPrDay&quot; },
        ///		{ Name: &quot;commitsPrUserLastMonth&quot; },
        ///		{ Name: &quot;commitsPrUserOverall&quot; },
        ///		{ Name: &quot;commitsPrUserLastSevenDays&quot; },
        ///		{ Name: &quot;commitsPrWeek&quot; }
        ///	]
        ///}]
        ///.
        /// </summary>
        internal static string Databases {
            get {
                return ResourceManager.GetString("Databases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///  Id: &quot;637e4a80-d700-46c7-b35a-96061bacbefc&quot;,
        ///  &quot;Date&quot;: &quot;\/Date(1281304800000+0200)\/&quot;,
        ///  &quot;NumberOfSales&quot;: 2
        ///}
        ///,
        ///{
        ///  Id: &quot;8313306a-f60e-438e-b640-ce5888ed377f&quot;,
        ///  &quot;Date&quot;: &quot;\/Date(1281218400000+0200)\/&quot;,
        ///  &quot;NumberOfSales&quot;: 6
        ///}
        ///,
        ///{
        ///  Id: &quot;5edff443-fde9-4813-a87e-ec0d19dd912a&quot;,
        ///  &quot;Date&quot;: &quot;\/Date(1281132000000+0200)\/&quot;,
        ///  &quot;NumberOfSales&quot;: 6
        ///}
        ///,
        ///{
        ///  Id: &quot;6472648d-0edf-4ffd-8eeb-fe99bc30d2f8&quot;,
        ///  &quot;Date&quot;: &quot;\/Date(1281045600000+0200)\/&quot;,
        ///  &quot;NumberOfSales&quot;: 4
        ///}
        ///,
        ///{
        ///  Id: &quot;a56115e6-3083-492 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ordersPrDay {
            get {
                return ResourceManager.GetString("ordersPrDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///Id: &quot;32966f74-b36a-438a-95d5-e1c17bcae93d&quot;,
        ///  &quot;Date&quot;: &quot;\/Date(1281304800000+0200)\/&quot;,
        ///  &quot;Revenue&quot;: 2244.0
        ///}
        ///,
        ///{
        ///Id: &quot;82d2413f-cedb-42f2-bdb5-f6f796b53425&quot;,
        ///  &quot;Date&quot;: &quot;\/Date(1281218400000+0200)\/&quot;,
        ///  &quot;Revenue&quot;: 2543.0
        ///}
        ///,
        ///{
        ///Id: &quot;faea37c0-21f4-4fb3-a6b8-80a60c681c4a&quot;,
        ///  &quot;Date&quot;: &quot;\/Date(1281132000000+0200)\/&quot;,
        ///  &quot;Revenue&quot;: 2743.0
        ///}
        ///,
        ///{
        ///Id: &quot;15977661-02b1-41e5-88e1-8e39f7746c09&quot;,
        ///  &quot;Date&quot;: &quot;\/Date(1281045600000+0200)\/&quot;,
        ///  &quot;Revenue&quot;: 3541.0
        ///}
        ///,
        ///{
        ///Id: &quot;8a6ef8cd-04a6-4232-a502-1a556b0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string revenuePrDay {
            get {
                return ResourceManager.GetString("revenuePrDay", resourceCulture);
            }
        }
    }
}
