//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeedee.Client.Web.Tests.RetrospectiveNoteRepositoryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smeedee.org", ConfigurationName="RetrospectiveNoteRepositoryService.RetrospectiveNoteRepositoryService")]
    public interface RetrospectiveNoteRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smeedee.org/RetrospectiveNoteRepositoryService/Get", ReplyAction="http://smeedee.org/RetrospectiveNoteRepositoryService/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Corkboard.RetrospectivePositiveNoteSpecification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Corkboard.RetrospectiveNegativeNoteSpecification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Corkboard.RetrospectiveNoteByDescriptionSpecification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Framework.AllSpecification<Smeedee.DomainModel.Corkboard.RetrospectiveNote>))]
        Smeedee.DomainModel.Corkboard.RetrospectiveNote[] Get(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.Corkboard.RetrospectiveNote> specification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smeedee.org/RetrospectiveNoteRepositoryService/Save", ReplyAction="http://smeedee.org/RetrospectiveNoteRepositoryService/SaveResponse")]
        void Save(Smeedee.DomainModel.Corkboard.RetrospectiveNote[] retrospectiveNote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smeedee.org/RetrospectiveNoteRepositoryService/Delete", ReplyAction="http://smeedee.org/RetrospectiveNoteRepositoryService/DeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Corkboard.RetrospectivePositiveNoteSpecification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Corkboard.RetrospectiveNegativeNoteSpecification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Corkboard.RetrospectiveNoteByDescriptionSpecification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Smeedee.DomainModel.Framework.AllSpecification<Smeedee.DomainModel.Corkboard.RetrospectiveNote>))]
        void Delete(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.Corkboard.RetrospectiveNote> specification);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RetrospectiveNoteRepositoryServiceChannel : Smeedee.Client.Web.Tests.RetrospectiveNoteRepositoryService.RetrospectiveNoteRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrospectiveNoteRepositoryServiceClient : System.ServiceModel.ClientBase<Smeedee.Client.Web.Tests.RetrospectiveNoteRepositoryService.RetrospectiveNoteRepositoryService>, Smeedee.Client.Web.Tests.RetrospectiveNoteRepositoryService.RetrospectiveNoteRepositoryService {
        
        public RetrospectiveNoteRepositoryServiceClient() {
        }
        
        public RetrospectiveNoteRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RetrospectiveNoteRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetrospectiveNoteRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetrospectiveNoteRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Smeedee.DomainModel.Corkboard.RetrospectiveNote[] Get(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.Corkboard.RetrospectiveNote> specification) {
            return base.Channel.Get(specification);
        }
        
        public void Save(Smeedee.DomainModel.Corkboard.RetrospectiveNote[] retrospectiveNote) {
            base.Channel.Save(retrospectiveNote);
        }
        
        public void Delete(Smeedee.DomainModel.Framework.Specification<Smeedee.DomainModel.Corkboard.RetrospectiveNote> specification) {
            base.Channel.Delete(specification);
        }
    }
}
