//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.GraphSampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class GraphSampleDataSource { }
#else

	public class GraphSampleDataSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public GraphSampleDataSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/Tskjortebutikken.Widgets.SL;component/SampleData/GraphSampleDataSource/GraphSampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private Data _Data = new Data();

		public Data Data
		{
			get
			{
				return this._Data;
			}
		}
	}

	public class DataItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _X = string.Empty;

		public string X
		{
			get
			{
				return this._X;
			}

			set
			{
				if (this._X != value)
				{
					this._X = value;
					this.OnPropertyChanged("X");
				}
			}
		}

		private double _Y = 0;

		public double Y
		{
			get
			{
				return this._Y;
			}

			set
			{
				if (this._Y != value)
				{
					this._Y = value;
					this.OnPropertyChanged("Y");
				}
			}
		}
	}

	public class Data : System.Collections.ObjectModel.ObservableCollection<DataItem>
	{ 
	}
#endif
}
