//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making 
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.UserSampleData
{
	using System;

	public class UserSampleData : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public UserSampleData()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/APD.Client.Widget.DeveloperInfo.SL;component/SampleData/UserSampleData/UserSampleData.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception )
			{ }
		}

		private string _Email = string.Empty;
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if (this._Email != value)
				{
					this._Email = value;
					this.OnPropertyChanged("Email");
				}
			}
		}

		private string _ImageUrl = string.Empty;
		public string ImageUrl
		{
			get
			{
				return this._ImageUrl;
			}
			set
			{
				if (this._ImageUrl != value)
				{
					this._ImageUrl = value;
					this.OnPropertyChanged("ImageUrl");
				}
			}
		}

		private string _Name = string.Empty;
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}
	}
}
