//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.UserdbSampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class UserdbSampleDataSource { }
#else

	public class UserdbSampleDataSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public UserdbSampleDataSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/APD.Client.Widget.Admin.SL;component/SampleData/UserdbSampleDataSource/UserdbSampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private Data _Data = new Data();

		public Data Data
		{
			get
			{
				return this._Data;
			}
		}

		private bool _DataIsChanged = false;

		public bool DataIsChanged
		{
			get
			{
				return this._DataIsChanged;
			}

			set
			{
				if (this._DataIsChanged != value)
				{
					this._DataIsChanged = value;
					this.OnPropertyChanged("DataIsChanged");
				}
			}
		}

		private DuckTypedData _DuckTypedData = new DuckTypedData();

		public DuckTypedData DuckTypedData
		{
			get
			{
				return this._DuckTypedData;
			}
		}
	}

	public class Data : System.Collections.ObjectModel.ObservableCollection<DataItem>
	{ 
	}

	public class DataItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Username = string.Empty;

		public string Username
		{
			get
			{
				return this._Username;
			}

			set
			{
				if (this._Username != value)
				{
					this._Username = value;
					this.OnPropertyChanged("Username");
				}
			}
		}

		private string _Email = string.Empty;

		public string Email
		{
			get
			{
				return this._Email;
			}

			set
			{
				if (this._Email != value)
				{
					this._Email = value;
					this.OnPropertyChanged("Email");
				}
			}
		}

		private string _Name = string.Empty;

		public string Name
		{
			get
			{
				return this._Name;
			}

			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}

		private string _ImageUrl = string.Empty;

		public string ImageUrl
		{
			get
			{
				return this._ImageUrl;
			}

			set
			{
				if (this._ImageUrl != value)
				{
					this._ImageUrl = value;
					this.OnPropertyChanged("ImageUrl");
				}
			}
		}
	}

	public class DuckTypedDataItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Email = string.Empty;

		public string Email
		{
			get
			{
				return this._Email;
			}

			set
			{
				if (this._Email != value)
				{
					this._Email = value;
					this.OnPropertyChanged("Email");
				}
			}
		}

		private string _ImageUrl = string.Empty;

		public string ImageUrl
		{
			get
			{
				return this._ImageUrl;
			}

			set
			{
				if (this._ImageUrl != value)
				{
					this._ImageUrl = value;
					this.OnPropertyChanged("ImageUrl");
				}
			}
		}

		private string _Name = string.Empty;

		public string Name
		{
			get
			{
				return this._Name;
			}

			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}

		private string _Username = string.Empty;

		public string Username
		{
			get
			{
				return this._Username;
			}

			set
			{
				if (this._Username != value)
				{
					this._Username = value;
					this.OnPropertyChanged("Username");
				}
			}
		}
	}

	public class DuckTypedData : System.Collections.ObjectModel.ObservableCollection<DuckTypedDataItem>
	{ 
	}
#endif
}
