//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APD.Client.WebTests.HolidayService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="HolidayService.HolidayRepositoryService")]
    public interface HolidayRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:HolidayRepositoryService/Get", ReplyAction="urn:HolidayRepositoryService/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(APD.DomainModel.Holidays.HolidaySpecification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(APD.DomainModel.Framework.AllSpecification<APD.DomainModel.Holidays.Holiday>))]
        System.Collections.Generic.List<APD.DomainModel.Holidays.Holiday> Get(APD.DomainModel.Framework.Specification<APD.DomainModel.Holidays.Holiday> specification);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:HolidayRepositoryService/Save", ReplyAction="urn:HolidayRepositoryService/SaveResponse")]
        void Save(System.Collections.Generic.List<APD.DomainModel.Holidays.Holiday> holidays);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HolidayRepositoryServiceChannel : APD.Client.WebTests.HolidayService.HolidayRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HolidayRepositoryServiceClient : System.ServiceModel.ClientBase<APD.Client.WebTests.HolidayService.HolidayRepositoryService>, APD.Client.WebTests.HolidayService.HolidayRepositoryService {
        
        public HolidayRepositoryServiceClient() {
        }
        
        public HolidayRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HolidayRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidayRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidayRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<APD.DomainModel.Holidays.Holiday> Get(APD.DomainModel.Framework.Specification<APD.DomainModel.Holidays.Holiday> specification) {
            return base.Channel.Get(specification);
        }
        
        public void Save(System.Collections.Generic.List<APD.DomainModel.Holidays.Holiday> holidays) {
            base.Channel.Save(holidays);
        }
    }
}
